apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-common-dev

resources:
  - ../../base
  - httproute.yaml

generators:
  - secret-generator.yaml

configMapGenerator:
  - name: api-common-config
    envs:
      - config.env

images:
  - name: ghcr.io/umc-commonplant/api-common
    newTag: sha-e0e8cada565e2e1c00a86d56da7ae3e6aa00b148

patches:
  - path: patch-deployment.yaml
