apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-common-dev

resources:
  - ../../base
  - httproute.yaml

generators:
  - secret-generator.yaml

configMapGenerator:
  - name: api-common-config
    envs:
      - config.env

images:
  - name: ghcr.io/umc-commonplant/api-common
    newTag: sha-101e9974ed9981a6786355c4a1b184e62c008588

patches:
  - path: patch-deployment.yaml
