apiVersion: viaduct.ai/v1
kind: ksops

metadata:
  name: api-common-secret-generator

  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops

secretFrom:
  - metadata:
      name: api-common-secret

      annotations:
        kustomize.config.k8s.io/needs-hash: "true"

    type: Opaque

    envs:
      - ./secret.enc.env