apiVersion: v1
kind: Secret
metadata:
    name: postgres-dev-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:eizNiIyrNw==,iv:+LTd5YXxbUympPTSBSY+nY1jQgQ3GsUV60Buo79kk3o=,tag:FIU9VPKsGrDq5zOJR4oTTw==,type:str]
    password: ENC[AES256_GCM,data:r/fAR7BPK6ZSLm3jHczIew==,iv:BSiBT+lHV83EiHV7Rd40BnE4UNXNYWbTl04n+S4QoSU=,tag:mXT9Ua5hRTg84ZVlNaNijQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0empOdEk0aVNySkM0YVFM
            bmhoNCsvWExiaFlaaitDMWFIZ0VLcTFRZldZCndhTDZ5OWR2dzBjQWFPUGNobzBh
            ckxSREhrdHpMc3ZHbFE3azBhRGcxSXMKLS0tIFh4MGZhZGl6SnUzQUhXbGlmRFAw
            azV1akhNY0U2Y1VwYlYvRVg1dXZSZkkKF6vmX151MwDJD8uNggtyD9PoYiFIz1kf
            IFuVJPt4tBBQTYeQ/fFxKFmMn5ODDaQHaHuRmYiHkrWzWuizXpcmpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbThCWkUrM3VONlo4dVdH
            OXJjWlBWNG81MnBzY20yRW1DY295VThLN3cwCmZrSFlMWU90eXdIcTMvL3dJZEdk
            Y2orcTNlUzJQRnlhVFN2UnlLa2pPREUKLS0tIHh1OUNrcGVrNU50M0hKbnB0Z3ln
            Sk1uc0lVNmcvbUVmSy9nRkM2VEhWWUkKZfd/qsIOjTUJSDQoRHbMOpmwLKESfFpI
            Ym+4rUo3o4GMmBHbOIgvO9EZdrVsV+qdt5NbhunIz7yWuYbqPRO5Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T05:17:11Z"
    mac: ENC[AES256_GCM,data:3JaDOmcb8/mfPvSSNoj7X5X5gZiePPAJpvFRbWzHRJVwJGP3XH9SamT0yI9AOM7dAwN0qgi0NEewME1eiAPAmTUV4IobNKX+P5fPYd3TO24O+eaF7B/KJxog3CZim6La4xcxXt4/zwDJluRdGAYCFH5FcggND/F0DiUzFDrQWL0=,iv:CnzNtVc1dZNyMj+La1H03bh8zAhbxm+6+UfnVdKTags=,tag:EDbamqYbdGVBZ0+tM1xDPQ==,type:str]
    version: 3.13.2
