apiVersion: v1
kind: Secret
metadata:
    name: postgres-dev-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:94tJDy6rJA==,iv:igLceZszsp6D2EjjD0Pk8JhjAUBxUYSWNZ9PYdvxNl8=,tag:kHpQFXjHemptOa31JVc4tA==,type:str]
    password: ENC[AES256_GCM,data:jEnO+4VsmpUacozPO32b9Q==,iv:I3V7z8wAgtV85yFKFBUZcAg4QlCWwKBd2UPAM1RAwkQ=,tag:KmWUGNqWW2qc7J3gwZexrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV3ZTWDhQL1N2MUxTNGht
            ZmFIUzJsTlJmcFJuNHZqYzVmdEFBTGJKdUJVCm44bnh3WGNWUkU2THNrZThjekpo
            VjYwcW1NNVdFTnlwNVVQK0Z5eTFEdHcKLS0tIE5wT1NhTGYrdXNYeDRhMzk1cXAz
            emNCOFcvQ2pCck0yOGp6TFRTS0xmQnMKSv+4fIX4nXi/3B+ON9Ms0qmfdoZQhutG
            L2e7fEvT49JRYin5p2DDlRsHE79pWR90Nk0PuxtZCDOedXDX61S8kQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNnhqOFJhWm5xdTJqT01G
            bFViVEYrTGlqREJTcTFqdGFQMU80YzdMWFVzCm1KemQ4ZXo1VkU5TVlaRlVHQlZ2
            YkF4TmN1aUlEL1k0c2dWMlJSYTJQa2cKLS0tIEdLQ01DY0JtYTlJQ0JldzRSK0sr
            Vmk1bVo4dE5BOXF6OU1nOUdlWTVxbzgKMbe0S1O1K9r5BkFlAIJf4kvt8VBbbkoP
            TMPHBGCCRSUID8IScBnzIEwrUbmqTg0nuRtrFusCTumpWmnllk1c6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T11:04:04Z"
    mac: ENC[AES256_GCM,data:K3iIfMTW4mQWfjR1IjIoOAUZcY/TtpB/VAlQFsk82qtwOkWPv8PHePNoVXuNBJo3ZNkRxRyZ2W2+bH9l6BxKDkSEEUW+ASeC9uXaGH1Uv++f5O+mb8LXRK6Mb96CRra/dp2aEezCkNKh3hoRRKub5nworOLJl6j2eOxboAMW5Js=,iv:Vk5jmYgbEOom8WrdrdcZUP/NwJZma4OT2f8+0vrfzNs=,tag:bHadzKbFPeMO72Gv2kTxbQ==,type:str]
    version: 3.13.2
