---
- name: 2. Bastion /etc/hosts 매핑 설치
  hosts: bastion
  become: true
  tags: [ bastion, bastion_hosts ]
  tasks:
    - name: Bastion hostname 해석 정보 관리
      ansible.builtin.import_role:
        name: bastion_hosts
        tasks_from: manage
