apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Production application workloads

  sourceRepos:
    - https://github.com/hweyoung/homelab.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: 'api-*-prod'

  clusterResourceBlacklist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment

    - group: ""
      kind: Service

    - group: ""
      kind: ServiceAccount

    - group: ""
      kind: ConfigMap

    - group: ""
      kind: LimitRange

    - group: ""
      kind: ResourceQuota

    - group: networking.k8s.io
      kind: NetworkPolicy

    - group: rbac.authorization.k8s.io
      kind: Role

    - group: rbac.authorization.k8s.io
      kind: RoleBinding

    - group: gateway.networking.k8s.io
      kind: HTTPRoute

  orphanedResources:
    warn: true
