apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: garage

resources:
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - proxy-service.yaml
  - proxy-deployment.yaml

configMapGenerator:
  - name: garage-web-proxy
    files:
      - nginx.conf=proxy-nginx.conf

labels:
  - pairs:
      app.kubernetes.io/name: garage
      app.kubernetes.io/instance: platform-garage
      app.kubernetes.io/part-of: object-storage
