apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: homelab.okbear.dev/environment
          operator: Exists
          effect: NoSchedule

        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule

      containers:
        - name: helper-pod
          image: busybox