apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie
  enableSuperuserAccess: false

  bootstrap:
    initdb:
      database: homelab
      owner: homelab
      dataChecksums: true

  storage:
    storageClass: local-path
    size: 10Gi

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
