namespaces:
  # ==================
  # Platform Namespace
  # ==================
  - name: infisical
    environment: prod
    gatewayAccess: public

  - name: openbao
    environment: prod
    gatewayAccess: public

  - name: external-secrets
    environment: prod
    gatewayAccess: public

  - name: garage
    environment: prod
    gatewayAccess: public

  # ==================
  # Homelab Workload Namespace
  # ==================
  - name: api-nginx-dev
    environment: dev
    gatewayAccess: public

  - name: api-nginx-prod
    environment: prod
    gatewayAccess: public

  # ==================
  # CommonPlant Application Namespace
  # ==================
  - name: api-common-dev
    environment: dev
    gatewayAccess: public

  - name: api-common-prod
    environment: prod
    gatewayAccess: public
