namespaces:
  # ==================
  # Homelab Workload Namespace
  # ==================
  - name: api-nginx-dev
    environment: dev
    gatewayAccess: public

  - name: api-nginx-prod
    environment: prod
    gatewayAccess: public