---
- name: Tailscale RPM 저장소 추가
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/rhel/9/tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo
    mode: "0644"

- name: Tailscale 패키지 설치
  ansible.builtin.dnf:
    name: tailscale
    state: present

- name: tailscaled 시작 및 활성화
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: true
