apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:PvKZk0lcpl4rZrMBcXxOSFqlw8uO47gkCqeOFbKB7glIs8/fGFxo8Vu57B760mGaUFkbnhRuw5Ptz9BVSFA15EDvXQ++6eZ5v852oUwZyJb2DLBsQSi5RMgoF8iG01Qzd4cZPnrVPC0W2OWTR8m/LAejAPd1f4iQ5QcU1OOHuLmEnxceCMEIvf0n22uXhGSxn3JrRbqgyoSuLnbklsgww5cNQeXPyQZuzewoZfzjCVTNv+1OFVeHc6Phb3oHDYTuCTkBhtuO/RvNdG1cWiLp36rfa3tfooNqvVasmy4/kSlvGNEEX6Jbx+zC5nE=,iv:ovJFXrjikiHn4wJpiYQCgaJtGPTPIzdnypBBNuytGKI=,tag:ZMJZJUcLgbsjpANfXFlRTA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMXdoVFRGSUFObzhOUXZo
            RVpIdlNkN2FXWTJ3cWp6L1RFN2lITlo3aXdjClI5MTR0ejdxNVJBZmNtZEFieGUy
            NGlyMnpQNmozc2JQYUNTQnZGaTA3WGMKLS0tIGxOdTRGWTFiWTYwWWt2L2hYNXR6
            Y3VJRzJ4dGxEc0VEb1FFb0RMeGtEMHcKvN9okdsOkKV+Afg6MBoa6mFwoiMQP1Ln
            AAT+R5guqqJIg9s11/zt99VU1e9/qarwUC2cXixbKfanPPW/2LxVMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaDZZTDhKUG5tTWNuVGtl
            YnFYV3RDblo2NThXZFc2bC8wNzIxUzlybVh3ClVUenZXWncrNG1ZOGUrVlArNkZq
            MmtmUXR5cGNSUHpVSm0vdFFRQWxhL2cKLS0tIEMwWExIaUtJd21MVmkyWVVTRmJB
            YlFscHMwd3dtMC9QWHpYRVBZSDE5TDAKeUD+5BrdfMYFBwhcuD8XeacnQKfjaTFZ
            c0H1wLXvl0NVB1shlXGHTkrQTEwWkj+GxUHrHemZcoXLR/NpMJXOgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T13:16:47Z"
    mac: ENC[AES256_GCM,data:ACIOkESArFr6uYbG/oYIh5BeEvLhj47Inqn8t2qVYQvnAd64mCnqElQITRFdDePwlEQ13t/sHpBe9nBLJIUgNsLnGN80+7CqRepR/YJqhPe4mxpsg3Ok9m4/Drrrzfe1tLdTlcw77GLVhM1iupDRf2Om/cjgBoykpNsApRUp1yE=,iv:coNN26ptXyVPzofnEoj9abQlfBNRx4ftBNswHdNK0/Q=,tag:KwcQJANcrr07upJTxHXyWg==,type:str]
    version: 3.13.2
