apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:5hVcnPRvSEXLRAVYqarXy6GSrtxKMKLi0wLOgoQjB5re3aZcw61KPhpQyaUmZqtNdEIuTz29oH3Dy7dgW3rQJficA3ry05CSsCtrQuTHB7jZNo/fYoeEwaPkSm0kn1IN2PYKVGela4adYt4Sid7JUiTTjVN25l74V5HkfBv3eWCM1rt3VkqRO4ltnCf+a3/mbiQw2V9dBnaUlN4L535Z23MUNxgIsuN4YudUnFYQ12FN+QSuVbqPulM9H/yB7+STTMAIWVW+Lk9WZ3Wa9ZwlqMmWDupvC3Xk3cCGsZwIMSRHRrKKJ9CGP/y11m5Uuqc1Vf9wM/hv2zul/9r+GVjVutKAxIPtEba2CcMnoJyd4JR/ITPfnGRMIyezB5rUcu+yVysqfqGLDB7sFaCDoccD1OIot7AcK/4kqtO2sGafABBwaCadAXPBx9lC4KX2AftCdTTXtY6OdG1RvU7rOCjBbQL73cV91Qpnt4pmj9LdOEeE8rO2GYQ0gVz7v9BWDKLafGRdd874ie46rOuPmk8qig==,iv:DKUIdOSYtV6bfuPthxM16WJ5OYkLj1bXXzLDIXmDrCw=,tag:EK0czib0EyeGU5MBhGsjOQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMEwwNVZSOUFnUUg2Vjhw
            MWpsVFpXeVNzTWwvRHFURVFkZC92RTUxQkNNCm10N1JheHlRQTZzRzZVZWJoMUZV
            bndFbHh4RjRXNzBIVnVORkhWZmdnMXcKLS0tIFpVWjNtRm50SGg5NEJnLzdabEc1
            SkxkQVVxNXFPREVkamNxOXpSTTcvTzgKEWwuy171NUakaTxTQLl2Qx0Wz4wmAgpW
            LwH9pl19XlQqab4ghh9keQ82c9llTx7SeLywzEGqp+sxCt1xbO9rGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVG1DTk44U3BnRTdORkw3
            TW56TGxCMmFjeEdlbG5IN3NTUDFCRHBLR0g0CkQ3enpGbTdxc253TkN5dVB2cDB1
            eUpjNGNOK1Z3M0FKdTRRaCt2M2RjRlkKLS0tIHZjWkFBdFp0RHVneHlPRnVDVi9L
            dHZqSGcrN2R5Rm5seW1TcFlKczFuSU0KSMlRgx5X7SVGFNmO6gzJM+NkY0823y90
            1qfatmtA1iwW2SmXQbYYQvQdF2YgI33BZtSbDnA6gscKSjWMjGWPlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T13:02:12Z"
    mac: ENC[AES256_GCM,data:75knZTrzvyTY6ZKrRS4s3/x+h32ZmyoLmd3CIHp/niul0jm1e+Twr3t6qwDrH0pfirKvoP8x2iHhBc0azMCKMDD1ZfLFXlTfuFYQfbBrqzt9SzxBmqt+7zBnYrCZ9vrfFVaS2gGCcTamyiy9upUT3JEe9+Di8Ym2K8qZ/OCDSG4=,iv:xKpsTE9I0zAbTpYdoRj0lc16Rc0RzvFXIjEVX5A1Oeo=,tag:5hDhcnSwGfjyjcGqc/xeng==,type:str]
    version: 3.13.2
