apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:C2mSYYZzY/gWU5DMcs3Ld9YC6CRPMtuSq5a6oySXP6/N4wukhgCMxq7gMFVbrhAK8nfGX7XrjLK9OjM1izXG0dAteYRhhfjZj8l8EpoqCkN1UwqNjHezSNa9yn0lxf/tmIDLlBiPwP4E+NS3sSIFXDO8oUdhQdPFXbyOQl9t1dz7H1frUabtvHQEXK/t4yGDvohR81jFD2KwFzYKlDHYWzXS2/9iRMQZnpSd7Q0V4uKY/vcc/IjOxXEyRyPBGJf6pk1C196r6iygr1JnJN7d5A7ZDeo/6IO0J6EFEGIBL3fhGOmlzwtQHfnxnGY65fiH75NZErF/YBGGTtY6GJuI+rt0cSYQ3gobl6wP6NQITWaUDDHU6jEMCmv7Xw9fZB6Bu5LZepx9tMXU4Ke6EneBOnbAbDI1Qt3AZBMCpt/6dqjDCGeWLBaYzQpXcPWiufp3l3m9r1+y6AaZ0TCeXnSENlbcK274KYf+V6zR+9BbQTRXXrCeEnY3HG2wyVzXLEWqj01z+/p/pGSVt99XATbVXA==,iv:RPvfIe3R0bJYq5uqc2bb/7KzfjLGvXK63d53YzAKe6g=,tag:Zr3pWmLi0hdvKZPiZXYJgw==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZmswekQrRlhTMkNzRHZv
            Zzh1S24rRVdQOWUxSmRralJaemgxUVVQeTFjCmtzditzYXIzRk9pTEcwSDl0VnhF
            T2NCRGZiRW4zeHh6NXdCbEQ3YkY0ZHcKLS0tIDM4Q1A2c0lSb1ZRMFRSVW03bVp1
            NUo5TEIyUWQ0by9tZHBvcHJ0S0Y5YjAK1seDZi34P64jwdn/rrqUJGkULUC+2aLx
            Zi9Z9M+B5RD/G5KUPvm3EBLrisbodEj/MCKjBXSsq8hQifOkdB4yKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K2I2WkJwWmV6VVBWdW5o
            dzFGTk1FSVNzelNiWGFXeG1TYkhRcVdxN2dJCjdlQmU1L2VjU3FnSEpaS0w2UUlX
            YW80MnkwOGxySHRQOVNWNXNoTVliWHMKLS0tIENXZElNVlZjam5XWnpiZWtsVjVt
            OUQ1YUg1dUxOcXRyY09Rdld4aWtUd28KAKaYz9NjYfLolppuOUd4qiaTEQlpom2T
            gv3RRnzhXTFmxp3qcq6p8wcziSJn7htZ0im3LWFuZuLYi9kZZnOpMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T12:49:09Z"
    mac: ENC[AES256_GCM,data:0r1OXXD/h7dElBPIj1aF0/YGj+A9LhuxbrFsN0+OcsaZwpFojpAp5DfO+6Gk3IQ0GGc3FICYUjYUHTS8lDgVkaAZOGrnC9PTHgiblZxfiQJ1/slHdYudEYbdyND34DMYfoucziGt+YIZ1xnht5yJzGWLqokgynm7Xr4t6/MPKac=,iv:aHLIJ5YeZpiyDkhv7OhLllvoVHt85a0l8OxxDLCftes=,tag:4MoQMcMoMQrSNVqpK/JdHg==,type:str]
    version: 3.13.2
