---
- import_tasks: prereq.yml
  tags: ['argocd', 'prereq']

- import_tasks: deploy.yml
  tags: ['argocd', 'deploy']

- import_tasks: root_app.yml
  tags: ['argocd', 'root_app', 'gitops']

- import_tasks: verify.yml
  tags: ['argocd', 'verify']
