apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infisical
nameSuffix: -infisical

resources:
  - ../../base

patches:
  - path: patch-cluster.yaml

generators:
  - postgres-infisical-secret-generator.yaml
