apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ixixPffhHA==,iv:OumpW8dtICpkKFqnXfCyk+RYIBFInESjZ37sl3msbz8=,tag:rAgfuP5LjReVKTbtB3QZNQ==,type:str]
    password: ENC[AES256_GCM,data:6MsRI0UQ1JagdzLnohxGcA==,iv:S/fYvNjy6eeBFmi42Ju0f96RZtGRG3d0a0sRd6T73Eo=,tag:avLFKcfrIXXWR7tcfNX0Dw==,type:str]
    uri: ENC[AES256_GCM,data:Cb0E9z9j0LnmJmflr9oorL+WPPSWNfazmuL0eQkA0KTNyLBYpulerUVTGsD3hP3ItNy28Zyyeyscn10piByB+R0jXo/arbRbS8IMTuElNd6wZxa/vsrC5qdcliyHLx1XdPXitUn4DzM=,iv:CSeDZASd1Yf1S6pBKfaNXkbmIrnzW3avXIGBuWC78zM=,tag:GxcMas270iIosAkul/VxNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVnBPbm5JMHo2VXBrY1dN
            Tzk4eVJvenU2cmpUQzNhYURDY0VNVXB1YWhFCkZIamhwVjZwN2dyUzlQRFNodTg1
            ME4vcjBRWE5BcGhpdkR2QzhBcDlnOEkKLS0tIGNySkRSVVRzWUlYQ0lLTWpMQTFN
            RDN4Vmhla25pdW8yMXh1VWh1U2wxMXMKk9/cOMMrlUO7NednZYdMAkcNt7oRMR73
            8P7e3sHuTOfKrsVdUKqRirbzA/gDSf8mbnt9NjWPkoQh/6WdO9oLKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdE9sNXA3bkVBeitKbEha
            SVJrOWVHZWwvaVB1VlFWN2NtaXMvL2ZqYVJ3Ci9KSm10NDdybHNaNE1hNWVyZ2h6
            cDZMUlBNY1B1UWxaUVR3V1hZa2wvZ2MKLS0tIHhUaGVGalVIdHhyTitESXRYL2Zx
            Z1N0SXFMSTV1TWgyeFVObnhUN2VqbXMK/YDJXyvP8DaNBXbbsK4SoUBFuMrS7Ho0
            rJkwpT8zC198N11GHYvpLrHsclgczoi08f1e1rLVHm0XveOx6uWP8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T09:13:10Z"
    mac: ENC[AES256_GCM,data:DpSt8IJWvsdO9ju6hL/jBwYgtCOGTIg8XI7GxSukiVnOuxK+lvsElr5RTva5zpK96Mi/E1x9T2ym6MBwyrv8VM45aVnn0hrDlF1e6eYNbnMNl764spyBZZuPs7AumftM7vSmtf5QZhBKw/sgMgR+cVsPYQpppHT735vJecsLzXE=,iv:7Hl/rsK/HheHSoleS6dXqcbLtWkf0ItjUsO+58rR60o=,tag:t1ODruHuaFDyDIrIA3IJRw==,type:str]
    version: 3.13.2
