apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:RIT/6XD8Hh70,iv:EpjhWwM98gFR/v8zfJdAnTWTOl74goicU82/GxJILiA=,tag:6V+4rF/TTJmojcg/r6sxSg==,type:str]
    password: ENC[AES256_GCM,data:Ok6QfagX84P/w57sABrsd74=,iv:aSs9TREeIuTYpRbuktHXPb+/FVq0qQbBKW3P+BHBkCk=,tag:mpAaqTcmbo/fm0OwLRqL/A==,type:str]
    uri: ENC[AES256_GCM,data:D0lLvhBGXWRWvEyVAisVw5uRpZ1kEWpPnNp7JdaK82+baWfnu9LLYmWtaMJH1GUPElWlxEtRaz0hyoPjZX67qBVvhmIZtD+7HO2JAztVkgS1xO3YDcEGvngOoQ==,iv:s2CS5LNWiQZDlCxD0oGCg3sMyabEx3wjMO9B0MvfpdQ=,tag:CoHNZCBsQL1HuuuYOThSQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVnBPbm5JMHo2VXBrY1dN
            Tzk4eVJvenU2cmpUQzNhYURDY0VNVXB1YWhFCkZIamhwVjZwN2dyUzlQRFNodTg1
            ME4vcjBRWE5BcGhpdkR2QzhBcDlnOEkKLS0tIGNySkRSVVRzWUlYQ0lLTWpMQTFN
            RDN4Vmhla25pdW8yMXh1VWh1U2wxMXMKk9/cOMMrlUO7NednZYdMAkcNt7oRMR73
            8P7e3sHuTOfKrsVdUKqRirbzA/gDSf8mbnt9NjWPkoQh/6WdO9oLKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdE9sNXA3bkVBeitKbEha
            SVJrOWVHZWwvaVB1VlFWN2NtaXMvL2ZqYVJ3Ci9KSm10NDdybHNaNE1hNWVyZ2h6
            cDZMUlBNY1B1UWxaUVR3V1hZa2wvZ2MKLS0tIHhUaGVGalVIdHhyTitESXRYL2Zx
            Z1N0SXFMSTV1TWgyeFVObnhUN2VqbXMK/YDJXyvP8DaNBXbbsK4SoUBFuMrS7Ho0
            rJkwpT8zC198N11GHYvpLrHsclgczoi08f1e1rLVHm0XveOx6uWP8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T09:37:41Z"
    mac: ENC[AES256_GCM,data:5hxSspZjwYQ1vOKaAeE0zYepQjsxjvY5frjSpaFaLe/bJqN5NNQiuwXAThfG2Tc8zLeGGq1Vy2KB/eprk6/ZNTo/a/Z00DFSpD82VYwxumLszJz18Ojdbhr9jIL5XjyJYxrlaCQ+73klcHN7LMBShtS8rt2DUAsQ8Y2uq7CaPv4=,iv:z+QscNU53Ydy1iQ/rzDX+VzMoxU7o+Cg/KSNHGfY++U=,tag:CnYZ47J7DGfsP51Gvcs2Hg==,type:str]
    version: 3.13.2
