apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: api-common-db-auth-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops

files:
  - ./db-auth-secret.sops.yaml