apiVersion: v1
kind: Secret
metadata:
    name: api-common-db-secret
    namespace: postgres-dev
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:u5BhavCbgqSORQ==,iv:/A5FTRK/1k+dOIYAearDQ9MX5JPSv5IySK+dYT5fXfY=,tag:Jnp6F3nU9SmDgrwNMFwMeg==,type:str]
    password: ENC[AES256_GCM,data:5j8UD1KL+4yWRccey24pY+XB,iv:BKjufRQMGDgb3kcMArNxKDLBJgOXHWadddGRdPeSVy4=,tag:eB9yegP0diniMMckcbRNTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Vk0xbmZ1ZlFwY1p3Snp2
            OSs5eDZRZlRnNVQzWHhBb3RqbFoxRVlmOWxJCktlUit5NUQ4K3I4c0tXVEkvblRU
            dkdrQnhtS0dRbGZMNkJYMldFZEhrYkUKLS0tIDBxTk1LZ3ozckRZVXJiUkNlSUZl
            RmlyRCt0Y09neHRNTVpkdmV6MXl3SmMKLDrbBEfRr6ybskVHq7RRXjx4AB8MPzEP
            xV03REWdYh1Mk0a6VMx3xDZCWsYmpbGmkNkJ7HwyS1b9rHQt0lVBdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheFlyK2pBL2syQzc2Y2po
            YzhLekRnOExhYm5pUUpVSmI0YlFneGdKVWpFClpVdkJNdDNxVFdEaW94YnJkVUVr
            alpnOGhVcWJUUC9jU0JCQXBOTEdwNXcKLS0tIGFMUUYxUGw1UkE3WDJDZjVtQnpQ
            SnJDSHNSNGlNT0FsV2loT0dnVmdUbUUKQLiBu/x0T1C4ed1GTQ+ZZ3z7Y0TCtP36
            q/TIndwPkjHZn8JnArn4QeZXwrjMcK11rFBmJtrGNB6/8xTHOiBTiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T10:50:26Z"
    mac: ENC[AES256_GCM,data:xAIdHmhu8o8GyWR1KQVoGSRAf7A6Ql7xUMCnuj0c4DBloLsxshG/a0IefjFc//+qfZwYcdYv2JWPOwDC/i1vUP5bhV8lmGztt1Gq4V37aWOqHAhmkidNt0ts1gYnHWV4QbjYa36ETRKrHI/ZfLzi2mS75a9daaulfGKIROt1HNA=,iv:kqtPTd2TGdE86+Tx+Eb4XDDN0c88KHdPsKEYwYrReyc=,tag:nfTcfrlNyocj9IUdj7xlbw==,type:str]
    version: 3.13.2
