apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-prod
nameSuffix: -prod

resources:
  - ../../base

patches:
  - path: patch-cluster.yaml

generators:
  - postgres-prod-secret-generator.yaml
