apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  storage:
    size: 20Gi

  bootstrap:
    initdb:
      database: homelab
      owner: homelab
      secret:
        name: postgres-prod-credentials
      dataChecksums: true
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

  affinity:
    nodeSelector:
      homelab.okbear.dev/environment: prod

    tolerations:
      - key: homelab.okbear.dev/environment
        operator: Equal
        value: prod
        effect: NoSchedule
