apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:q5f9YdsbXw==,iv:Le7gSkWE4hpD3RU+l1QOC/XPnfMj9BryDIS4isfTEac=,tag:0K99Nb+8VFxwS2hx/HBQUQ==,type:str]
    password: ENC[AES256_GCM,data:lSBA/AdMREiXQ6S7qRMVGw==,iv:/nA07O6UdqOtwaLQ1xMcNFUYvGf5ydEKpGPg43GphXM=,tag:3d3K4oGsfVx/ywZ2q3SaUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWmpIaTl1WXdQenVURWdm
            ZUFxNHRVV0xmRzhjMTdDRTJpaFoyNHRQN213Cll1R3MwMkZ3WFYyanV5S1FhUGRZ
            UzEzdmRZZVAxc0ZOL0VtUmlNOXlReW8KLS0tIDlJZGdGNUhlRTFuZ1gxRDl0T2JU
            QnJpNTBkMWFNbzZZSGJubkRpNzJBaE0KD+YOvdnQ3iPaPyjKSUYIWROrrqz7E+gX
            NH7IiU5jJDz8JQOL/6dd4eZxLgDTZOLUPFbqjgFOs6P1OU3fPjxxZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSDZkTndrNTE4Q1prRVB0
            YWRUWEtBOHNmalRLS0NyemJycTh1YklNL3lVCllVZHFMUmlVMEVwYllnYVRwTnIz
            am15emR6YzE4cGh5ZTF0TGJ1MlROZWsKLS0tIEJKdWJuYjVlbmFuWkdoRFdEWnEx
            bmlDNHRLejBuZ283aytFMktKZ25EeEEK/fleCvJjU1zFVV1dJVPjoJL0lceqlf9q
            Uh2XRaeelXKiKKUQebQ7WCGaSf3MwwTvCCLCoHQ9ahfKvuBuHdKpLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T11:04:18Z"
    mac: ENC[AES256_GCM,data:C+MzIoJMVmZT8KeTFSm78iSZ4PT8i3/u3o82hjHFlzW+T+u2RqshJIq62mVzXRE2vwBGi2YgrVAtIy4sIO+g4xdWFrk3MgLDlXjISOFb+C6xQMW+/eN+q4lEP4T47RRWcvniU/QUYkPdAa/AGVj9SUd/jy1w98ZI3EmZeNElyII=,iv:HhNiOa7D7gB7SEucN1/pVPK1ABhx+rVQjObjHv8Yjkc=,tag:U3g6QYIE1ImRpKge997vQQ==,type:str]
    version: 3.13.2
