apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:zTmr4i3gBg==,iv:Cp47sbthf5SRU7BDUKmO3lKJ4uejO/cJHgrIlKZ4+is=,tag:IPV/kwm+oxyLatIK0jK4dw==,type:str]
    password: ENC[AES256_GCM,data:woQjJTTiT43RP07Wx/O6mw==,iv:yjL9/EBcXGbDN5+4NU60GKvIhdyKkax4ARVafCglfg0=,tag:gm635Y2ea2vhTRx42b0Uvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTnFlRnJYRmp6WGFYa1dT
            akpObFVGS3c1enVhdjh6QTNVUzN6cld6YlhjCmJWV3k3M1JPb3B4eXdYNjBwL1ZD
            RXBPWUxwMVZVVW95cU1BRjhKNmZFRUUKLS0tIEpNT0czSzdXMDJJMFVRdTRzNEI1
            QVdyVWg4bTQ2OFh6VlhIUGw4VGZQNTQKtsGRib30S9KDuhql9S+mx6fqwzaCsslB
            jRkH9r8Q2RHRUN1XIArrP399cE8eYySicwsaGUxAIklzFCDw41pbRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaUVNL0lFSU53M1N5Ympp
            R1pMVDFkMGJLdXM4VTBkRmJXODZzR2Y3c0E4CkI1cXB1TVpCN3Bmd3RwRkxhUjBu
            NEdodzRQRGZ4KzNyV2Y0UWx6MXNxR28KLS0tICtZQ3I3MmxYd1E1T3k4OU4vTFNT
            eFQ4R1FJdExaYS9FUCtuNGNrckhLeDQKGa+ymObi9KNerbN2EG9tLaG9iiyK2xh7
            ehBq604DwI2gMNje1ByvI3VAKqIC6+SdZ2bsKzjdGy5+aoBpuU6mMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T05:33:24Z"
    mac: ENC[AES256_GCM,data:1iMmi/gkY0ADV1n6+XkAH/GK/TQvL1TmJC6qlDpF2V+oW5REXgt7/9iVvJXKyl9up3/ADa4HX10FBrFMD8FGYFDzd0HBimWOSPlztRkRx8zBUwsCknVmsr5AAwaFwFOTlRvr8VPl/meG3IGqOPZh3/JfyWX1WgP5P2RJcqxa5rQ=,iv:0yDaqjbeSJcrDz8YWtEohrdB/iw1QkzlShG7dXVzbTg=,tag:EX0JlxQ4EFqvQZt2FF1KLw==,type:str]
    version: 3.13.2
