apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: postgres-prod-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./postgres-prod-credentials.sops.yaml