apiVersion: v1
kind: Secret
metadata:
    name: postgres-prod-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:XdOEgoGY0Q==,iv:fY7UPTX2RKZI0ZBKH/ntqhLR0rj+kMmg/cpnVbGfdq0=,tag:mcd+jV5bAnjCsNSlytczxw==,type:str]
    password: ENC[AES256_GCM,data:44PmYkYMm06GWqegKK+Pqg==,iv:zbMSD4FZMgbR0zdGommnhR1Wm1SieHrkIZuJDxys+6A=,tag:DYx0JxAMPwloymavs0lKTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT3dvRXhtSTNJZUpGWDY3
            MWtBK3dia3ArSTlINVlpeTc2WDRFL1U4OFFzCkpYcTBONEEyelBtSjNjZGsxTzNC
            MWdtWjlzd2x4bjg3S1NOZEt1TENmcGsKLS0tIElFUkJqdVRib3J3WFlJdVhTUHBD
            WVVmbU91eitkRWR4VzdlL3E3cFhNaDAKXRE25qCx1CQC5hB0Y6OOxA77eYJhoe8F
            TFi1ex9GpdqeSD+ifBR/+8GxNp4kPDYKe00sEWU7nzfTKfR7E7aIzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgecp2wajurrqlc3rmkcuvelfkrs9vvquat0yv9qhs4wh3ahddsq6a9tfq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV3h2NjRtMi9tQ1ZDcE9U
            eHRmSlRVNUY5alZackp3T0dUcWRnWGhJUVRVClZtM0RCdFFUb1lYRXBUL0JtMG9S
            Q2YxcEZrQ3JHNVo2bEZyM0pyNk0vK2sKLS0tIDZ2bFJob09vRlJDUHkvZGtDS1k0
            cjdMYWNtMEw1Ly9kb0UwNFVKYWZyMkEKBP2SnW1vSqG+US29zoX5fTi387lUmj69
            /5oSTjtqAvE5MLeVKiNn3JJYXR7Iaq7ZeHA0ohMmVd+3g5OaOzUHHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suf4u08wu9yvhrmszaxcu342nlywwhn4u5q5qdhd220ap8remassd3jz6v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T05:16:42Z"
    mac: ENC[AES256_GCM,data:WE4YFWCj/wy0bAG3KZ91OyJzlVCAdykWnxTT+5OfMSyh1ySbR3nDG1AJTxsnZ7Bk2OnUHK/YUShxiZYyoaXmNHzu9DEvUU+STTuEFDnT3mrnHIUiwv55bmZmGaDG+sSSVnNH4PbJXXAME9x2KwXe3tvbM5pNsolhvfTrN/YIRik=,iv:6/xFGP4hRmEfPpLGQplaCHwP754UXsBQMjAVrPJT3WM=,tag:3rsNvJitzaD9xpord8+/OQ==,type:str]
    version: 3.13.2
